const iconDatabase = [
    { label: 'Person in Suit Levitating', icon: '🕴️' },
    { label: 'Person Climbing', icon: '🧗' },
    { label: 'Man Climbing', icon: '🧗‍♂️' },
    { label: 'Woman Climbing', icon: '🧗‍♀️' },
    { label: 'Person Fencing', icon: '🤺' },
    { label: 'Horse Racing', icon: '🏇' },
    { label: 'Skier', icon: '⛷️' },
    { label: 'Snowboarder', icon: '🏂' },
    { label: 'Person Golfing', icon: '🏌️' },
    { label: 'Man Golfing', icon: '🏌️‍♂️' },
    { label: 'Woman Golfing', icon: '🏌️‍♀️' },
    { label: 'Person Surfing', icon: '🏄' },
    { label: 'Man Surfing', icon: '🏄‍♂️' },
    { label: 'Woman Surfing', icon: '🏄‍♀️' },
    { label: 'Person Rowing Boat', icon: '🚣' },
    { label: 'Man Rowing Boat', icon: '🚣‍♂️' },
    { label: 'Woman Rowing Boat', icon: '🚣‍♀️' },
    { label: 'Person Swimming', icon: '🏊' },
    { label: 'Man Swimming', icon: '🏊‍♂️' },
    { label: 'Woman Swimming', icon: '🏊‍♀️' },
    { label: 'Person Bouncing Ball', icon: '⛹️' },
    { label: 'Man Bouncing Ball', icon: '⛹️‍♂️' },
    { label: 'Woman Bouncing Ball', icon: '⛹️‍♀️' },
    { label: 'Person Lifting Weights', icon: '🏋️' },
    { label: 'Man Lifting Weights', icon: '🏋️‍♂️' },
    { label: 'Woman Lifting Weights', icon: '🏋️‍♀️' },
    { label: 'Person Biking', icon: '🚴' },
    { label: 'Man Biking', icon: '🚴‍♂️' },
    { label: 'Woman Biking', icon: '🚴‍♀️' },
    { label: 'Person Mountain Biking', icon: '🚵' },
    { label: 'Man Mountain Biking', icon: '🚵‍♂️' },
    { label: 'Woman Mountain Biking', icon: '🚵‍♀️' },
    { label: 'Person Cartwheeling', icon: '🤸' },
    { label: 'Man Cartwheeling', icon: '🤸‍♂️' },
    { label: 'Woman Cartwheeling', icon: '🤸‍♀️' },
    { label: 'People Wrestling', icon: '🤼' },
    { label: 'Women Wrestling', icon: '🤼‍♀️' },
    { label: 'Person Playing Water Polo', icon: '🤽' },
    { label: 'Man Playing Water Polo', icon: '🤽‍♂️' },
    { label: 'Woman Playing Water Polo', icon: '🤽‍♀️' },
    { label: 'Person Playing Handball', icon: '🤾' },
    { label: 'Man Playing Handball', icon: '🤾‍♂️' },
    { label: 'Woman Playing Handball', icon: '🤾‍♀️' },
    { label: 'Person Juggling', icon: '🤹' },
    { label: 'Man Juggling', icon: '🤹‍♂️' },
    { label: 'Woman Juggling', icon: '🤹‍♀️' },
    { label: 'Person in Lotus Position', icon: '🧘' },
    { label: 'Man in Lotus Position', icon: '🧘‍♂️' },
    { label: 'Woman in Lotus Position', icon: '🧘‍♀️' },
    { label: 'Circus Tent', icon: '🎪' },
    { label: 'Skateboard', icon: '🛹' },
    { label: 'Roller Skate', icon: '🛼' },
    { label: 'Canoe', icon: '🛶' },
    { label: 'Reminder Ribbon', icon: '🎗️' },
    { label: 'Admission Tickets', icon: '🎟️' },
    { label: 'Ticket', icon: '🎫' },
    { label: 'Military Medal', icon: '🎖️' },
    { label: 'Trophy', icon: '🏆' },
    { label: 'Sports Medal', icon: '🏅' },
    { label: '1st Place Medal', icon: '🥇' },
    { label: '2nd Place Medal', icon: '🥈' },
    { label: '3rd Place Medal', icon: '🥉' },
    { label: 'Soccer Ball', icon: '⚽' },
    { label: 'Baseball', icon: '⚾' },
    { label: 'Softball', icon: '🥎' },
    { label: 'Basketball', icon: '🏀' },
    { label: 'Volleyball', icon: '🏐' },
    { label: 'American Football', icon: '🏈' },
    { label: 'Rugby Football', icon: '🏉' },
    { label: 'Tennis', icon: '🎾' },
    { label: 'Flying Disc', icon: '🥏' },
    { label: 'Bowling', icon: '🎳' },
    { label: 'Cricket Game', icon: '🏏' },
    { label: 'Field Hockey', icon: '🏑' },
    { label: 'Ice Hockey', icon: '🏒' },
    { label: 'Lacrosse', icon: '🥍' },
    { label: 'Ping Pong', icon: '🏓' },
    { label: 'Badminton', icon: '🏸'},
    { label: 'Boxing Glove', icon: '🥊' },
    { label: 'Martial Arts Uniform', icon: '🥋' },
    { label: 'Goal Net', icon: '🥅' },
    { label: 'Flag in Hole', icon: '⛳' },
    { label: 'Ice Skate', icon: '⛸️' },
    { label: 'Fishing Pole', icon: '🎣' },
    { label: 'Running Shirt', icon: '🎽' },
    { label: 'Skis', icon: '🎿' },
    { label: 'Sled', icon: '🛷' },
    { label: 'Curling Stone', icon: '🥌' },
    { label: 'Bullseye', icon: '🎯' },
    { label: 'Pool 8 Ball', icon: '🎱' },
    { label: 'Video Game', icon: '🎮' },
    { label: 'Slot Machine', icon: '🎰' },
    { label: 'Game Die', icon: '🎲' },
    { label: 'Puzzle Piece', icon: '🧩' },
    { label: 'Mirror Ball', icon: '🪩' },
    { label: 'Chess Pawn', icon: '♟️' },
    { label: 'Performing Arts', icon: '🎭' },
    { label: 'Artist Palette', icon: '🎨' },
    { label: 'Thread', icon: '🧵' },
    { label: 'Yarn', icon: '🧶' },
    { label: 'Musical Score', icon: '🎼' },
    { label: 'Microphone', icon: '🎤' },
    { label: 'Headphone', icon: '🎧' },
    { label: 'Saxophone', icon: '🎷' },
    { label: 'Accordion', icon: '🪗' },
    { label: 'Guitar', icon: '🎸' },
    { label: 'Musical Keyboard', icon: '🎹' },
    { label: 'Trumpet', icon: '🎺' },
    { label: 'Violin', icon: '🎻' },
    { label: 'Flute', icon: '🪈' },
    { label: 'Drum', icon: '🥁' },
    { label: 'Long Drum', icon: '🪘' },
    { label: 'Maracas', icon: '🪇' },
    { label: 'Clapper Board', icon: '🎬' },
    { label: 'Bow and Arrow', icon: '🏹' },
    ];

export default iconDatabase;