const emojiDatabase = [
    { label: 'Exercise regularly', icon: '🏋️‍♀️' },
    { label: 'Read more books', icon: '📚' },
    { label: 'Travel the world', icon: '✈️' },
    { label: 'Learn a new language', icon: '🗣️' },
    { label: 'Volunteer for a cause', icon: '🤝' },
    { label: 'Start a business', icon: '📈' },
    { label: 'Save money', icon: '💰' },
    { label: 'Learn to play a musical instrument', icon: '🎵' },
    { label: 'Write a book', icon: '📝' },
    { label: 'Learn to code', icon: '💻' },
    { label: 'Eat healthier', icon: '🥗' },
    { label: 'Master a new skill', icon: '🎯' },
    { label: 'Complete a marathon', icon: '🏅' },
    { label: 'Improve time management', icon: '⏰' },
    { label: 'Practice meditation', icon: '🧘‍♀️' },
    { label: 'Learn to cook gourmet meals', icon: '🍽️' },
    { label: 'Get organized', icon: '🗂️' },
    { label: 'Learn photography', icon: '📷' },
    { label: 'Start a YouTube channel', icon: '🎥' },
    { label: 'Learn to dance', icon: '💃' },
    { label: 'Learn to swim', icon: '🏊‍♀️' },
    { label: 'Adopt a healthier lifestyle', icon: '🌿' },
    { label: 'Complete a DIY project', icon: '🛠️' },
    { label: 'Improve public speaking skills', icon: '🎙️' },
    { label: 'Learn a martial art', icon: '🥋' },
    { label: 'Get a promotion at work', icon: '📈' },
    { label: 'Learn to play chess', icon: '♟️' },
    { label: 'Volunteer abroad', icon: '🌍' },
    { label: 'Become a better listener', icon: '👂' },
    { label: 'Start a garden', icon: '🌱' },
    { label: 'Learn graphic design', icon: '🎨' },
    { label: 'Get organized digitally', icon: '💻' },
    { label: 'Start a blog', icon: '✍️' },
    { label: 'Learn to drive', icon: '🚗' },
    { label: 'Learn to juggle', icon: '🤹‍♀️' },
    { label: 'Learn a new sport', icon: '🎾' },
    { label: 'Improve public speaking skills', icon: '🎤' },
    { label: 'Develop a morning routine', icon: '☀️' },
    { label: 'Learn to sew or knit', icon: '🧵' },
    { label: 'Practice mindfulness', icon: '☁️' },
    { label: 'Start a podcast', icon:'🎙️' },
    { label: 'Improve financial literacy', icon: '💵' },
    { label: 'Learn to do yoga', icon: '🧘‍♀️' },
    { label: 'Learn to ski or snowboard', icon: '⛷️🏂' },
    { label: 'Complete a home renovation', icon: '🏡' },
    { label: 'Learn to play poker', icon: '♠️♥️♦️♣️' },
    { label: 'Volunteer at a local shelter', icon: '🏠🐾' },
    { label: 'Start a collection', icon: '🖼️' },
    { label: 'Learn to do magic tricks', icon: '🎩' },
    { label: 'Pursue higher education', icon: '🎓' },

    //Wellness Goals
    { label: 'Drink more water', icon: '🚰' },
    { label: 'Eat more fruits and vegetables', icon: '🍎' },
    { label: 'Exercise regularly', icon: '🏋️‍♂️' },
    { label: 'Get enough sleep', icon: '💤' },
    { label: 'Practice mindfulness', icon: '🌞' },
    { label: 'Reduce stress', icon: '😌' },
    { label: 'Meditate daily', icon: '🌈' },
    { label: 'Go for a walk', icon: '🚶‍♂️' },
    { label: 'Practice yoga', icon: '⭐️' },
    { label: 'Take breaks from screens', icon: '📵' },
    { label: 'Practice deep breathing', icon: '🌬️' },
    { label: 'Get regular check-ups', icon: '👩‍⚕️' },
    { label: 'Maintain a balanced diet', icon: '🍽️' },
    { label: 'Reduce caffeine intake', icon: '☕' },
    { label: 'Get outdoors', icon: '🌳' },
    { label: 'Practice self-care', icon: '💆‍♀️' },
    { label: 'Try new healthy recipes', icon: '🥗' },
    { label: 'Get involved in a hobby', icon: '🎨' },
    { label: 'Limit screen time', icon: '📱' },
    { label: 'Practice gratitude', icon: '🙏' },
    { label: 'Engage in regular physical activity', icon: '🏃‍♀️' },
    { label: 'Reduce alcohol consumption', icon: '🍷' },
    { label: 'Improve posture', icon: '🧍‍♀️' },
    { label: 'Practice good hygiene', icon: '🧼' },
    { label: 'Maintain a healthy weight', icon: '⚖️' },
    { label: 'Stay socially connected', icon: '👥' },
    { label: 'Get regular massages', icon: '💆‍♂️' },
    { label: 'Take time for relaxation', icon: '🌅' },
    { label: 'Avoid excessive sugar intake', icon: '🍭' },
    { label: 'Practice positive affirmations', icon: '🌟' },
    { label: 'Prioritize self-care', icon: '🌸' },


    //Professional Goals
    { label: 'Get a promotion', icon: '🚀' },
    { label: 'Enhance leadership skills', icon: '👑' },
    { label: 'Improve communication', icon: '💬' },
    { label: 'Learn a new programming language', icon: '💻' },
    { label: 'Expand professional network', icon: '🤝' },
    { label: 'Complete professional certifications', icon: '📜' },
    { label: 'Master time management', icon: '⏰' },
    { label: 'Improve public speaking', icon: '🎙️' },
    { label: 'Develop negotiation skills', icon: '💼' },
    { label: 'Enhance project management skills', icon: '📊' },
    { label: 'Improve problem-solving abilities', icon: '🔎' },
    { label: 'Learn data analysis', icon: '📊' },
    { label: 'Start a side business', icon: '📈' },
    { label: 'Become a mentor', icon: '🙌' },
    { label: 'Learn financial management', icon: '💰' },
    { label: 'Improve teamwork skills', icon: '🤝' },
    { label: 'Develop marketing skills', icon: '📈' },
    { label: 'Become an industry expert', icon: '🔍' },
    { label: 'Enhance creative thinking', icon: '💡' },
    { label: 'Improve customer service skills', icon: '👥' },
    { label: 'Learn new software tools', icon: '💻' },
    { label: 'Stay updated with industry trends', icon: '📰' },
    { label: 'Enhance organizational skills', icon: '🗄️' },
    { label: 'Improve presentation skills', icon: '📊' },
    { label: 'Learn project management methodologies', icon: '📚' },
    { label: 'Expand knowledge in a specific domain', icon: '🔍' },
    { label: 'Become a better listener', icon: '👂' },
    { label: 'Enhance critical thinking', icon: '🔍' },
    { label: 'Learn new design techniques', icon: '🎨' },
    { label: 'Improve decision-making skills', icon: '🔍' },
    { label: 'Develop strategic planning abilities', icon: '📈' },
    ];

export default emojiDatabase;