const iconDatabase = [
    { label: 'Trophy', icon: '🏆' },
    { label: 'Graduation Cap', icon: '🎓' },
    { label: 'Books', icon: '📚' },
    { label: 'Briefcase', icon: '💼' },
    { label: 'Lightbulb', icon: '💡' },
    { label: 'Rocket', icon: '🚀' },
    { label: 'Money Bag', icon: '💰' },
    { label: 'Magnifying Glass', icon: '🔍' },
    { label: 'Calendar', icon: '📅' },
    { label: 'Sparkles', icon: '✨' },
    { label: 'Fire', icon: '🔥' },
    { label: 'Star', icon: '⭐' },
    { label: 'Rainbow', icon: '🌈' },
    { label: 'Gem Stone', icon: '💎' },
    { label: 'Locked', icon: '🔒' },
    { label: 'Seedling', icon: '🌱' },
    { label: 'Microscope', icon: '🔬' },
    { label: 'High Voltage', icon: '⚡' },
    { label: 'Clipboard', icon: '📋' },
    { label: 'Laptop', icon: '💻' },
    { label: 'Mobile Phone', icon: '📱' },
    { label: 'Hourglass', icon: '⌛' },
    { label: 'Key', icon: '🔑' },
    { label: 'Brain', icon: '🧠' },
    { label: 'Hammer', icon: '🔨' },
    { label: 'Chart Increasing', icon: '📈' },
    { label: 'Wrench', icon: '🔧' },
    { label: 'Desktop Computer', icon: '🖥️' },
    { label: 'Bar Chart', icon: '📊' },
    { label: 'Notebook', icon: '📔' },
    { label: 'Alarm Clock', icon: '⏰' },
    { label: 'Film Projector', icon: '📽️' },
    { label: 'Running Shoe', icon: '👟' },
    { label: 'Weight Lifting', icon: '🏋️‍♂️' },
    { label: 'Water Wave', icon: '🌊' },
    { label: 'Apple', icon: '🍎' },
    { label: 'Hospital', icon: '🏥' },
    { label: 'Heart', icon: '❤️' },
    { label: 'Running', icon: '🏃' },
    { label: 'Vegetable', icon: '🥦' },
    { label: 'Stethoscope', icon: '🩺' },
    { label: 'Yoga', icon: '🧘' },
    { label: 'Water Bottle', icon: '🚰' },
    { label: 'Green Salad', icon: '🥗' },
    { label: 'Syringe', icon: '💉' },
    { label: 'Heartbeat', icon: '💓' },
    { label: 'Basketball', icon: '🏀' },
    { label: 'Running Track', icon: '🏃‍♂️' },
    { label: 'Swimmer', icon: '🏊' },
    { label: 'Medicine', icon: '💊' },
    { label: 'Heart Eyes', icon: '😍' },
    { label: 'Doctor', icon: '👨‍⚕️' },
    { label: 'Weight Scale', icon: '⚖️' },
    { label: 'Sports Medal', icon: '🏅' },
    { label: 'Biking', icon: '🚴' },
    { label: 'Lotus Position', icon: '🧘‍♀️' },
    { label: 'Square', icon: '▪️' },
    { label: 'Circle', icon: '⚪' },
    { label: 'Triangle', icon: '🔺' },
    { label: 'Hexagon', icon: '🔳' },
    { label: 'Pentagon', icon: '⬟' },
    { label: 'Check Mark', icon: '✅' },
    { label: 'Dollar Banknote', icon: '💵' },
    { label: 'Euro Banknote', icon: '💶' },
    { label: 'Pound Banknote', icon: '💷' },
    { label: 'Yen Banknote', icon: '💴' },
    { label: 'Money with Wings', icon: '💸' },
  ];
  
  export default iconDatabase;