const goalsCategoryDatabase = [
  { label: 'Professional', icon: '💼' },
  { label: 'Extracurricular', icon: '🎉' },
  { label: 'Health and Wellness', icon: '🌿' },
  { label: 'Financial', icon: '💰' },
  { label: 'Education', icon: '🎓' },
  { label: 'Relationships', icon: '👫' },
  { label: 'Personal Growth', icon: '🌱' },
  { label: 'Fitness', icon: '🏋️' },
  { label: 'Hobbies', icon: '🎨' },
  { label: 'Travel', icon: '✈️' },
  { label: 'Community Involvement', icon: '🤝' },
  { label: 'Creativity', icon: '🎭' },
  { label: 'Organization and Productivity', icon: '🗄️' },
  { label: 'Family', icon: '👨‍👩‍👧‍👦' },
  { label: 'Self-Care', icon: '🧖‍♀️' },
  { label: 'Skills Development', icon: '📚' },
  { label: 'Socializing', icon: '🎊' },
  { label: 'Philanthropy', icon: '🙏' },
  { label: 'Career Advancement', icon: '🚀' },
  { label: 'Adventure', icon: '🌍' },
  { label: 'Wellness Practices', icon: '🧘' },
  { label: 'Financial Independence', icon: '🏦' },
  { label: 'Academic Achievement', icon: '🎒' },
  { label: 'Friendships', icon: '👯' },
  { label: 'Creativity and Arts', icon: '🎨' },
  { label: 'Time Management', icon: '⏰' },
  { label: 'Parenting', icon: '👪' },
  { label: 'Mental Health', icon: '🧠' },
  { label: 'Physical Fitness', icon: '🏃' },
  { label: 'Leisure and Entertainment', icon: '🎮' },
  { label: 'Volunteering', icon: '🙌' },
  { label: 'Personal Development', icon: '🌟' },
  { label: 'Sports', icon: '⚽' },
  { label: 'Financial Stability', icon: '📈' },
  { label: 'Lifelong Learning', icon: '📖' },
  { label: 'Romance', icon: '💑' },
  { label: 'Artistic Pursuits', icon: '🖌️' },
  { label: 'Productivity', icon: '✅' },
  { label: 'Sustainability', icon: '🌍' },
  { label: 'Entrepreneurship', icon: '💡' },
  { label: 'Outdoor Activities', icon: '🏞️' },
  { label: 'Spirituality', icon: '🕉️' },
  { label: 'Skill Building', icon: '🔧' },
  { label: 'Social Skills', icon: '🤝' },
  { label: 'Home Improvement', icon: '🏠' },
  { label: 'Work-Life Balance', icon: '⚖️' },
  { label: 'Music', icon: '🎵' },
  { label: 'Giving Back', icon: '🎁' },
  { label: 'Fashion', icon: '👗' },
  { label: 'Language Learning', icon: '🗣️' },
  { label: 'Culinary Skills', icon: '🍳' },
  { label: 'Environmental Conservation', icon: '🌳' },
  { label: 'Networking', icon: '🤝' },
  { label: 'Pet Care', icon: '🐾' },
  { label: 'Other', icon: '✅' },
];

export default goalsCategoryDatabase;

